2025-05-18 17:24:52,308 ERROR frappe Failed to run after request hook
Site: test6.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 196, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 211, in make_session
    frappe.local.session_obj = Session(
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 230, in __init__
    self.resume()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    data = self.get_session_record()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 326, in get_session_record
    r = self.get_session_data()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 343, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 374, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 455, in get_expired_threshold
    now = frappe.utils.now()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 313, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.now(pytz.UTC))
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 328, in get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 325, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'
2025-05-18 17:24:53,109 ERROR frappe Failed to run after request hook
Site: test6.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 196, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 211, in make_session
    frappe.local.session_obj = Session(
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 230, in __init__
    self.resume()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    data = self.get_session_record()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 326, in get_session_record
    r = self.get_session_data()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 343, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 374, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 455, in get_expired_threshold
    now = frappe.utils.now()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 313, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.now(pytz.UTC))
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 328, in get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 325, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'
2025-05-18 17:24:53,504 ERROR frappe Failed to run after request hook
Site: test6.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 196, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 211, in make_session
    frappe.local.session_obj = Session(
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 230, in __init__
    self.resume()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    data = self.get_session_record()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 326, in get_session_record
    r = self.get_session_data()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 343, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 374, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 455, in get_expired_threshold
    now = frappe.utils.now()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 313, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.now(pytz.UTC))
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 328, in get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 325, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'
2025-05-18 17:24:53,760 ERROR frappe Failed to run after request hook
Site: test6.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 196, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 211, in make_session
    frappe.local.session_obj = Session(
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 230, in __init__
    self.resume()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    data = self.get_session_record()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 326, in get_session_record
    r = self.get_session_data()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 343, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 374, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 455, in get_expired_threshold
    now = frappe.utils.now()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 313, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.now(pytz.UTC))
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 328, in get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 325, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'
2025-05-18 17:25:35,804 ERROR frappe Failed to run after request hook
Site: test6.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 196, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 211, in make_session
    frappe.local.session_obj = Session(
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 230, in __init__
    self.resume()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    data = self.get_session_record()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 326, in get_session_record
    r = self.get_session_data()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 343, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 374, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 455, in get_expired_threshold
    now = frappe.utils.now()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 313, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.now(pytz.UTC))
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 328, in get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 325, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'
2025-05-18 17:25:36,083 ERROR frappe Failed to run after request hook
Site: test6.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 196, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 211, in make_session
    frappe.local.session_obj = Session(
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 230, in __init__
    self.resume()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    data = self.get_session_record()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 326, in get_session_record
    r = self.get_session_data()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 343, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 374, in get_session_data_from_db
    .where(sessions.lastupdate > get_expired_threshold())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 455, in get_expired_threshold
    now = frappe.utils.now()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 361, in now
    return now_datetime().strftime(DATETIME_FORMAT)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 313, in now_datetime
    dt = convert_utc_to_system_timezone(datetime.datetime.now(pytz.UTC))
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 348, in convert_utc_to_system_timezone
    time_zone = get_system_timezone()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/data.py", line 328, in get_system_timezone
    return frappe.get_system_settings("time_zone") or "Asia/Kolkata"  # Default to India ?!
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 325, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management.hooks'
2025-05-18 17:34:19,428 ERROR frappe Failed to run after request hook
Site: test6.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 100, in application
    init_request(request)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 196, in init_request
    frappe.local.http_request = HTTPRequest()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 44, in __init__
    self.set_session()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 78, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 117, in __init__
    self.make_session(resume=True)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/auth.py", line 211, in make_session
    frappe.local.session_obj = Session(
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 230, in __init__
    self.resume()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 313, in resume
    self.validate_user()
  File "/home/limendo/frappe-bench/apps/frappe/frappe/sessions.py", line 238, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1236, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 133, in application
    response = handle_exception(e)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/permissions.py", line 870, in wrapper
    return fn(e, *args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 325, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 2328, in get_system_settings
    local.system_settings = system_settings = get_cached_doc("System Settings")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1179, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1305, in get_doc
    return frappe.model.document.get_doc(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/document.py", line 83, in get_doc
    controller = get_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 71, in get_controller
    site_controllers[doctype] = import_controller(doctype)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/model/base_document.py", line 89, in import_controller
    class_overrides = frappe.get_hooks("override_doctype_class")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 147, in application
    run_after_request_hooks(request, response)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/app.py", line 162, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1607, in get_hooks
    hooks = _dict(_load_app_hooks())
  File "/home/limendo/frappe-bench/apps/frappe/frappe/utils/caching.py", line 59, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1576, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/limendo/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'library_management'
2025-05-19 08:44:33,965 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"LMS00002","owner":"Administrator","creation":"2025-05-19 14:14:29.193494","modified":"2025-05-19 14:14:29.193494","modified_by":"Administrator","docstatus":0,"idx":0,"library_member":"LM00014","full_name":"Sreeja G","from":"2025-05-21","to_date":"2025-05-30","paid":1,"amended_from":null,"doctype":"Library Membership","__last_sync_on":"2025-05-19T08:44:29.875Z"}', 'action': 'Submit', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 08:45:20,533 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"LMS00003","owner":"Administrator","creation":"2025-05-19 14:15:17.252451","modified":"2025-05-19 14:15:17.252451","modified_by":"Administrator","docstatus":0,"idx":0,"library_member":"LM00012","full_name":"Dev Test","from":"2025-05-27","to_date":"2025-05-31","paid":1,"amended_from":null,"doctype":"Library Membership","__last_sync_on":"2025-05-19T08:45:17.889Z"}', 'action': 'Submit', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 08:47:19,055 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"LMS00003","owner":"Administrator","creation":"2025-05-19 14:15:17.252451","modified":"2025-05-19 14:15:17.252451","modified_by":"Administrator","docstatus":0,"idx":0,"library_member":"LM00012","full_name":"Dev Test","from":"2025-05-27","to_date":"2025-05-31","paid":1,"amended_from":null,"doctype":"Library Membership","__last_sync_on":"2025-05-19T08:45:17.889Z"}', 'action': 'Submit', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 08:48:51,050 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"LMS00004","owner":"Administrator","creation":"2025-05-19 14:18:47.607287","modified":"2025-05-19 14:18:47.607287","modified_by":"Administrator","docstatus":0,"idx":0,"library_member":"LM00012","full_name":"Dev Test","from":"2025-05-19","to_date":"2025-05-31","paid":1,"amended_from":null,"doctype":"Library Membership","__last_sync_on":"2025-05-19T08:48:48.255Z"}', 'action': 'Submit', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 08:51:05,807 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"LMS00001","owner":"Administrator","creation":"2025-05-19 14:21:02.708187","modified":"2025-05-19 14:21:02.708187","modified_by":"Administrator","docstatus":0,"idx":0,"library_member":"LM00014","full_name":"Sreeja G","from":"2025-05-19","to_date":"2025-05-31","paid":1,"amended_from":null,"doctype":"Library Membership","__last_sync_on":"2025-05-19T08:51:03.360Z"}', 'action': 'Submit', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 08:52:35,083 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"LMS00001","owner":"Administrator","creation":"2025-05-19 14:21:02.708187","modified":"2025-05-19 14:21:02.708187","modified_by":"Administrator","docstatus":0,"idx":0,"library_member":"LM00014","full_name":"Sreeja G","from":"2025-05-19","to_date":"2025-05-31","paid":1,"doctype":"Library Membership","__last_sync_on":"2025-05-19T08:52:32.046Z"}', 'action': 'Submit', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 08:59:57,821 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"Library Transaction","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-15 17:14:19.336788","modified_by":"Administrator","owner":"Administrator","docstatus":0,"idx":0,"issingle":0,"is_virtual":0,"is_tree":0,"istable":0,"editable_grid":0,"track_changes":0,"module":"Library Management","naming_rule":"","sort_field":"modified","sort_order":"DESC","read_only":0,"in_create":0,"allow_copy":0,"allow_rename":1,"allow_import":0,"hide_toolbar":0,"track_seen":0,"max_attachments":0,"document_type":"","engine":"InnoDB","is_submittable":0,"show_name_in_global_search":0,"custom":0,"beta":0,"has_web_view":0,"allow_guest_to_view":0,"email_append_to":0,"show_title_field_in_link":0,"translated_doctype":0,"is_calendar_and_gantt":0,"quick_entry":0,"grid_page_length":50,"track_views":0,"queue_in_background":0,"allow_events_in_timeline":0,"allow_auto_repeat":0,"make_attachments_public":0,"force_re_route_to_default_view":0,"show_preview_popup":0,"protect_attached_files":0,"index_web_pages_for_search":1,"row_format":"Dynamic","doctype":"DocType","fields":[{"docstatus":0,"doctype":"DocField","name":"new-docfield-xtgjxgcmxx","__islocal":1,"__unsaved":1,"owner":"Administrator","fieldtype":"Link","precision":"","non_negative":0,"hide_days":0,"hide_seconds":0,"reqd":0,"is_virtual":0,"search_index":0,"sort_options":0,"show_dashboard":0,"fetch_if_empty":0,"hidden":0,"show_on_timeline":0,"bold":0,"allow_in_quick_entry":0,"translatable":0,"print_hide":0,"print_hide_if_no_value":0,"report_hide":0,"collapsible":0,"hide_border":0,"in_list_view":0,"in_standard_filter":0,"in_preview":0,"in_filter":1,"in_global_search":0,"read_only":0,"allow_on_submit":0,"ignore_user_permissions":0,"allow_bulk_edit":0,"make_attachment_public":0,"permlevel":0,"ignore_xss_filter":0,"unique":0,"no_copy":0,"set_only_once":0,"remember_last_selected_value":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":1,"fieldname":"article","label":"Article","options":"Article","show_preview_popup":0,"columns":0,"length":0},{"docstatus":0,"doctype":"DocField","name":"new-docfield-sacfoizrki","__islocal":1,"__unsaved":1,"owner":"Administrator","fieldtype":"Link","precision":"","non_negative":0,"hide_days":0,"hide_seconds":0,"reqd":0,"is_virtual":0,"search_index":0,"sort_options":0,"show_dashboard":0,"fetch_if_empty":0,"hidden":0,"show_on_timeline":0,"bold":0,"allow_in_quick_entry":0,"translatable":0,"print_hide":0,"print_hide_if_no_value":0,"report_hide":0,"collapsible":0,"hide_border":0,"in_list_view":0,"in_standard_filter":0,"in_preview":0,"in_filter":0,"in_global_search":0,"read_only":0,"allow_on_submit":0,"ignore_user_permissions":0,"allow_bulk_edit":0,"make_attachment_public":0,"permlevel":0,"ignore_xss_filter":0,"unique":0,"no_copy":0,"set_only_once":0,"remember_last_selected_value":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":2,"fieldname":"library_member","label":"Library Member","options":"Library Member","show_preview_popup":0,"columns":0,"length":0},{"docstatus":0,"doctype":"DocField","name":"new-docfield-evoytysyba","__islocal":1,"__unsaved":1,"owner":"Administrator","fieldtype":"Select","precision":"","non_negative":0,"hide_days":0,"hide_seconds":0,"reqd":0,"is_virtual":0,"search_index":0,"sort_options":0,"show_dashboard":0,"fetch_if_empty":0,"hidden":0,"show_on_timeline":0,"bold":0,"allow_in_quick_entry":0,"translatable":0,"print_hide":0,"print_hide_if_no_value":0,"report_hide":0,"collapsible":0,"hide_border":0,"in_list_view":0,"in_standard_filter":0,"in_preview":0,"in_filter":0,"in_global_search":0,"read_only":0,"allow_on_submit":0,"ignore_user_permissions":0,"allow_bulk_edit":0,"make_attachment_public":0,"permlevel":0,"ignore_xss_filter":0,"unique":0,"no_copy":0,"set_only_once":0,"remember_last_selected_value":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":3,"fieldname":"type","label":"Type","options":"Issue\\nReturn","show_preview_popup":0,"columns":0,"length":0},{"docstatus":0,"doctype":"DocField","name":"new-docfield-fwxrqoghqb","__islocal":1,"__unsaved":1,"owner":"Administrator","fieldtype":"Date","precision":"","non_negative":0,"hide_days":0,"hide_seconds":0,"reqd":0,"is_virtual":0,"search_index":0,"sort_options":0,"show_dashboard":0,"fetch_if_empty":0,"hidden":0,"show_on_timeline":0,"bold":0,"allow_in_quick_entry":0,"translatable":0,"print_hide":0,"print_hide_if_no_value":0,"report_hide":0,"collapsible":0,"hide_border":0,"in_list_view":0,"in_standard_filter":0,"in_preview":0,"in_filter":0,"in_global_search":0,"read_only":0,"allow_on_submit":0,"ignore_user_permissions":0,"allow_bulk_edit":0,"make_attachment_public":0,"permlevel":0,"ignore_xss_filter":0,"unique":0,"no_copy":0,"set_only_once":0,"remember_last_selected_value":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":4,"fieldname":"date_of_transaction","label":"Date of Transaction","show_preview_popup":0,"columns":0,"length":0}],"links":[],"permissions":[{"name":"79ij85i8pv","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-15 17:14:19.336788","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"permissions","parenttype":"DocType","idx":1,"permlevel":0,"role":"System Manager","read":1,"write":1,"create":1,"submit":0,"cancel":0,"delete":1,"amend":0,"report":1,"export":1,"import":0,"share":1,"print":1,"email":1,"if_owner":0,"select":0,"doctype":"DocPerm"}],"actions":[],"states":[],"__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 09:01:38,266 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"Library Transaction","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:29:57.660468","modified_by":"Administrator","owner":"Administrator","docstatus":0,"idx":0,"issingle":0,"is_virtual":0,"is_tree":0,"istable":0,"editable_grid":0,"track_changes":0,"module":"Library Management","naming_rule":"Expression (old style)","sort_field":"modified","sort_order":"DESC","read_only":0,"in_create":0,"allow_copy":0,"allow_rename":1,"allow_import":0,"hide_toolbar":0,"track_seen":0,"max_attachments":0,"document_type":"","engine":"InnoDB","is_submittable":0,"show_name_in_global_search":0,"custom":0,"beta":0,"has_web_view":0,"allow_guest_to_view":0,"email_append_to":0,"show_title_field_in_link":0,"translated_doctype":0,"is_calendar_and_gantt":0,"quick_entry":0,"grid_page_length":50,"track_views":0,"queue_in_background":0,"allow_events_in_timeline":0,"allow_auto_repeat":0,"make_attachments_public":0,"force_re_route_to_default_view":0,"show_preview_popup":0,"protect_attached_files":0,"index_web_pages_for_search":1,"row_format":"Dynamic","doctype":"DocType","fields":[{"name":"vk8amsl8a4","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:29:57.660468","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":1,"fieldname":"article","label":"Article","fieldtype":"Link","options":"Article","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":1,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"},{"name":"vk8erc0uka","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:29:57.660468","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":2,"fieldname":"library_member","label":"Library Member","fieldtype":"Link","options":"Library Member","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":0,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"},{"name":"vk839h7tcu","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:29:57.660468","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":3,"fieldname":"type","label":"Type","fieldtype":"Select","options":"Issue\\nReturn","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":0,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"},{"name":"vk8tptmhr6","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:29:57.660468","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":4,"fieldname":"date_of_transaction","label":"Date of Transaction","fieldtype":"Date","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":0,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"}],"links":[],"permissions":[{"name":"79ij85i8pv","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:29:57.660468","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"permissions","parenttype":"DocType","idx":1,"permlevel":0,"role":"System Manager","read":1,"write":1,"create":1,"submit":0,"cancel":0,"delete":1,"amend":0,"report":1,"export":1,"import":0,"share":1,"print":1,"email":1,"if_owner":0,"select":0,"doctype":"DocPerm"}],"actions":[],"states":[],"__unsaved":1,"autoname":"LMR.#####"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-19 09:03:09,972 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"name":"Library Transaction","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:31:38.185121","modified_by":"Administrator","owner":"Administrator","docstatus":0,"idx":0,"issingle":0,"is_virtual":0,"is_tree":0,"istable":0,"editable_grid":0,"track_changes":0,"module":"Library Management","autoname":"LMR.#####","naming_rule":"Expression (old style)","sort_field":"modified","sort_order":"DESC","read_only":0,"in_create":0,"allow_copy":0,"allow_rename":1,"allow_import":0,"hide_toolbar":0,"track_seen":0,"max_attachments":0,"document_type":"","engine":"InnoDB","is_submittable":0,"show_name_in_global_search":0,"custom":0,"beta":0,"has_web_view":0,"allow_guest_to_view":0,"email_append_to":0,"show_title_field_in_link":0,"translated_doctype":0,"is_calendar_and_gantt":0,"quick_entry":0,"grid_page_length":50,"track_views":0,"queue_in_background":0,"allow_events_in_timeline":0,"allow_auto_repeat":0,"make_attachments_public":0,"force_re_route_to_default_view":0,"show_preview_popup":0,"protect_attached_files":0,"index_web_pages_for_search":1,"row_format":"Dynamic","doctype":"DocType","fields":[{"name":"vk8amsl8a4","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:31:38.185121","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":1,"fieldname":"article","label":"Article","fieldtype":"Link","options":"Article","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":1,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"},{"name":"vk8erc0uka","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:31:38.185121","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":2,"fieldname":"library_member","label":"Library Member","fieldtype":"Link","options":"Library Member","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":0,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"},{"name":"vk839h7tcu","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:31:38.185121","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":3,"fieldname":"type","label":"Type","fieldtype":"Select","options":"Issue\\nReturn","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":0,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"},{"name":"vk8tptmhr6","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:31:38.185121","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"fields","parenttype":"DocType","idx":4,"fieldname":"date_of_transaction","label":"Date of Transaction","fieldtype":"Date","search_index":0,"show_dashboard":0,"hidden":0,"set_only_once":0,"allow_in_quick_entry":0,"print_hide":0,"report_hide":0,"reqd":0,"bold":0,"in_global_search":0,"collapsible":0,"unique":0,"no_copy":0,"allow_on_submit":0,"show_preview_popup":0,"permlevel":0,"ignore_user_permissions":0,"columns":0,"in_list_view":0,"fetch_if_empty":0,"in_filter":0,"remember_last_selected_value":0,"ignore_xss_filter":0,"print_hide_if_no_value":0,"allow_bulk_edit":0,"in_standard_filter":0,"in_preview":0,"read_only":0,"precision":"","length":0,"translatable":0,"hide_border":0,"hide_days":0,"hide_seconds":0,"non_negative":0,"is_virtual":0,"sort_options":0,"show_on_timeline":0,"make_attachment_public":0,"doctype":"DocField"}],"links":[],"permissions":[{"name":"79ij85i8pv","creation":"2025-05-15 16:57:52.219998","modified":"2025-05-19 14:31:38.185121","modified_by":"Administrator","owner":"Administrator","docstatus":0,"parent":"Library Transaction","parentfield":"permissions","parenttype":"DocType","idx":1,"permlevel":0,"role":"System Manager","read":1,"write":1,"create":1,"submit":0,"cancel":0,"delete":1,"amend":0,"report":1,"export":1,"import":0,"share":1,"print":1,"email":1,"if_owner":0,"select":0,"doctype":"DocPerm"},{"docstatus":0,"doctype":"DocPerm","name":"new-docperm-swfzotnbgt","__islocal":1,"__unsaved":1,"owner":"Administrator","if_owner":0,"permlevel":0,"select":0,"read":1,"write":1,"create":1,"delete":1,"submit":0,"cancel":0,"amend":0,"report":1,"export":1,"import":0,"share":1,"print":1,"email":1,"parent":"Library Transaction","parentfield":"permissions","parenttype":"DocType","idx":2,"__unedited":false,"role":"Librarian"}],"actions":[],"states":[],"__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2025-05-21 06:45:20,690 ERROR frappe New Exception collected in error log
Site: test6.com
Form Dict: {'doc': '{"docstatus":0,"doctype":"Library Member","name":"new-library-member-cuknrbswzf","__islocal":1,"__unsaved":1,"owner":"Administrator","first_name":"Sathwik","last_name":"G","phone":"09573785559","email":"sathwik@outlook.com"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
